---
# Copyright 2024 Cisco Systems Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Read transport_url from mounted secret file
  ansible.builtin.slurp:
    src: /var/lib/openstack/configs/neutron-opflex-agent-custom-service/transport_url
  register: slurp_transport_url
  failed_when: not slurp_transport_url.content
  delegate_to: localhost

- name: Set transport_url fact from slurped content
  ansible.builtin.set_fact:
    edpm_cisco_neutron_opflex_DEFAULT_transport_url: "{{ slurp_transport_url.content | b64decode }}"

- name: Assert Variables are Set
  ansible.builtin.assert:
    that:
      - edpm_cisco_neutron_opflex_image != ""
    fail_msg: "'edpm_cisco_neutron_opflex_image' must be set."

- name: Bootstrap ciscoaci-neutron-opflex-agent
  ansible.builtin.import_tasks: bootstrap.yml

- name: Install ciscoaci-neutron-opflex-agent
  ansible.builtin.import_tasks: install.yml

- name: Configure ciscoaci-neutron-opflex-agent
  ansible.builtin.import_tasks: configure.yml

- name: Ensure ciscoaci-neutron-opflex-agent is running
  ansible.builtin.import_tasks: run.yml